[package]
name = "au-trx"
version = "0.2.0"
edition = "2021"

[dependencies]
ctrlc = "3.4.5"
gen-id = "0.2.1"
rtrb = "0.3.1"
frame-header = { git = "ssh://git@github.com/wavey-ai/frame-header.git" }
tracing = "0.1.41"
